[workspace]
members = [
  "maple-core",
  "maple-core-macro",
  "examples/components",
  "examples/counter",
  "examples/hello",
  "examples/ssr",
  "examples/todomvc",
  "docs",
]

[profile.release]
lto = true
opt-level = "z"
