name: Test

on: [push, pull_request]

env:
  RUSTFLAGS: -Dwarnings
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build
        run: cargo build
        if: always()

      - name: Run tests
        run: cargo test
        if: always()

      - name: Run headless browser tests
        run: wasm-pack test maple-core --firefox --chrome --headless
        if: always()

      - name: Run clippy
        run: cargo clippy
        if: always()
